### ISSUE TITLE
is py-graphql-client compatible with apollo-server-express?

### ISSUE THREAD

**Issue by scosean** [ecthiender/py-graphql-client#10] opened 2019-05-25 01:11 UTC
https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-express

**Comment by ecthiender** [comment] 2019-05-25 14:57
@scosean Yes it should be. :) py-graphql-client follows the apollo protocol. Try it out, report issues if it doesn't work? I will be happy to fix them.

**Comment by scosean** [comment] 2019-05-26 16:14
@ecthiender BTW, Thanks for creating and working on this library!
I created an apollo server and am able to successfully create a subscription to it using the apollo UI at localhost:4000/graphql but am not able to connect to the subscription using py-graphql-client

Apollo server:
https://gist.github.com/scosean/ac26539afde465cfa2760395aafd7627

**Comment by ecthiender** [comment] 2019-05-27 10:41
@scosean I will check it out. Thanks for reporting it.

**Comment by cyril94440** [comment] 2019-09-18 15:11
Hi there,

exact same issue for me. Apollo UI working well but can't make it work with this lib.

**Comment by scosean** [comment] 2019-09-18 17:16
@cyril94440 It started working for me after this commit: https://github.com/ecthiender/py-graphql-client/commit/88b3cd8151aabec537b61ca9e178e7afd1780cd9

**Comment by oscar6echo** [comment] 2020-03-23 22:00
It still does not work for me - while it is working fine from the apollo server playground.

Here are the logs from the websocket connection:
```bash
client - state = CONNECTING
client - event = connection_made(<_SelectorSocketTransport fd=7 read=idle write=<idle, bufsize=0>>)
client > GET /graphql HTTP/1.1
client > Headers([('Host', 'localhost:4000'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'tGzf0Ifir6g24UsPHf6Psw=='), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.8 websockets/8.1')])
client - event = data_received(<129 bytes>)
client < HTTP/1.1 101 Switching Protocols
client < Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', '4b4fXlOLDS+uKPoj27Wy2wHiSkw=')])
client - state = OPEN
--------------------------------------------------
client > Frame(fin=True, opcode=1, data=b'{"type": "connection_init", "payload": {}}', rsv1=False, rsv2=False, rsv3=False)
client - event = data_received(<4 bytes>)
client < Frame(fin=True, opcode=8, data=b'\x03\xea', rsv1=False, rsv2=False, rsv3=False)
client - state = CLOSING
client > Frame(fin=True, opcode=8, data=b'\x03\xea', rsv1=False, rsv2=False, rsv3=False)
client - event = eof_received()
client - event = connection_lost(None)
client - state = CLOSED
client x code = 1002, reason = [no reason]
``` 

Note that the message that triggers the close is the same (as much as I can see) as the one from the playground in the browser devtools:

![image](https://user-images.githubusercontent.com/2219383/77367167-dddd3480-6d59-11ea-9f74-11c82228cc11.png)

What could be the reason ? This is puzzling and blocking me.  
Any idea most welcome !

**Comment by ecthiender** [comment] 2020-03-28 19:26
@oscar6echo I fixed a bunch of bugs and released a new beta version.

You can install using: `pip install py-graphql-client==0.1.1b1` .

Can you try this and let me know? If this fixes the issue, then I'll publish a stable version.

Thanks!

**Comment by oscar6echo** [comment] 2020-03-28 19:53
Yes I realized that the fix mentionned by @scosean which indeed solves the problem, was *not* published. Now it works. Thx !

**Comment by ecthiender** [comment] 2020-03-31 17:48
@oscar6echo thanks for confirming that it is working!

I am closing this issue, as this library is confirmed to work with Apollo server.

**Closed as completed by ecthiender** 2020-03-31 17:48 UTC
Labels: question
